### ISSUE TITLE
Morning-session partners code review - Desktop Version

### ISSUE THREAD

**Issue by mullenlucas** [joa-byte/portfolio-mobile-version#3]
Very good code overall, neatly organized !

1. One tiny observation I could make is, for example here:

https://github.com/joa-byte/portfolio-mobile-version/blob/7b185cdd7d4492ef5abed80c303e12d6a7565b1d/index.html#L60

Instead of assigning a class to the `<ul>`, in order to not overuse classes, you could try styling it through sub-classes, like so:

```
.project-info ul {
  ...
  styling
  ...
}
```

2. Another detail is at the footer section, there is a `<div>` that contains the same thing as the `<footer>` tag, so it would be possible to remove that `<div>` and just use the `<footer>` tag for styling

Other than that great code !

**Comment by MishDM** [comment]
It's good and structured code writing. Keep it up !!
 When you name a certain class it has to be descriptive
 (**_ul class="lenguajes-list"_**)
